# Generated by Django 5.1.4 on 2025-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="firebase_uid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
