# Generated by Django 5.1.4 on 2025-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
